Wine.create(name:'Non Bere',year:1902,winery:'Esportiamo La Spazzatura',country:'Italy',varietal:'Cabernet')
Wine.create(name:'Feccia Ribelle',year:1802,winery:'Cantina Immondo',country:'Italy',varietal:'Pinot Noir')
Wine.create(name:'Exodus',year:1902,winery:'Jah Mondavi',country:'Jamaica',varietal:'Chardonnay')
Wine.create(name:'Raging Stitch',year:1972,winery:'Flying Carp',country:'USA',varietal:'Champagne')
Wine.create(name:'Fava Bean Surprise',year:1971,winery:'Hannibal Orchards',country:'USA',varietal:'Chianti')
Wine.create(name:'Two Buck Chuck',year:1902,winery:'Charles Shawsome',country:'USA',varietal:'Pinot Grigio')